# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SystemGainUi.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import Icon

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1010, 945)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Image/Icon/SAIC.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(40, 40))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter_centralwidget = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_centralwidget.setOrientation(QtCore.Qt.Vertical)
        self.splitter_centralwidget.setObjectName("splitter_centralwidget")
        self.MainStackedWidget = QtWidgets.QStackedWidget(self.splitter_centralwidget)
        self.MainStackedWidget.setObjectName("MainStackedWidget")
        self.Data_Viewer_page = QtWidgets.QWidget()
        self.Data_Viewer_page.setObjectName("Data_Viewer_page")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Data_Viewer_page)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_Data_Viewer_page = QtWidgets.QSplitter(self.Data_Viewer_page)
        self.splitter_Data_Viewer_page.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_Data_Viewer_page.setObjectName("splitter_Data_Viewer_page")
        self.Data_Viewer_CheckBox_scrollArea = QtWidgets.QScrollArea(self.splitter_Data_Viewer_page)
        self.Data_Viewer_CheckBox_scrollArea.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.Data_Viewer_CheckBox_scrollArea.setWidgetResizable(True)
        self.Data_Viewer_CheckBox_scrollArea.setObjectName("Data_Viewer_CheckBox_scrollArea")
        self.Data_Viewer_CheckBox_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.Data_Viewer_CheckBox_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 956, 749))
        self.Data_Viewer_CheckBox_scrollAreaWidgetContents.setObjectName("Data_Viewer_CheckBox_scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.Data_Viewer_CheckBox_scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Data_Viewer_CheckBox_groupBox = QtWidgets.QGroupBox(self.Data_Viewer_CheckBox_scrollAreaWidgetContents)
        self.Data_Viewer_CheckBox_groupBox.setMinimumSize(QtCore.QSize(150, 0))
        self.Data_Viewer_CheckBox_groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Data_Viewer_CheckBox_groupBox.setObjectName("Data_Viewer_CheckBox_groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Data_Viewer_CheckBox_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addWidget(self.Data_Viewer_CheckBox_groupBox, 0, 0, 1, 1)
        self.Data_Viewer_CheckBox_scrollArea.setWidget(self.Data_Viewer_CheckBox_scrollAreaWidgetContents)
        self.layoutWidget = QtWidgets.QWidget(self.splitter_Data_Viewer_page)
        self.layoutWidget.setObjectName("layoutWidget")
        self.Data_Viewer_page_graphicsView_LayV = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.Data_Viewer_page_graphicsView_LayV.setContentsMargins(0, 0, 0, 0)
        self.Data_Viewer_page_graphicsView_LayV.setObjectName("Data_Viewer_page_graphicsView_LayV")
        self.horizontalLayout.addWidget(self.splitter_Data_Viewer_page)
        self.MainStackedWidget.addWidget(self.Data_Viewer_page)
        self.System_Gain_page = QtWidgets.QWidget()
        self.System_Gain_page.setObjectName("System_Gain_page")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.System_Gain_page)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.System_Gain_PT_Choose = QtWidgets.QTabWidget(self.System_Gain_page)
        self.System_Gain_PT_Choose.setTabPosition(QtWidgets.QTabWidget.West)
        self.System_Gain_PT_Choose.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.System_Gain_PT_Choose.setObjectName("System_Gain_PT_Choose")
        self.System_Gain_AT_DCT_tab = QtWidgets.QWidget()
        self.System_Gain_AT_DCT_tab.setObjectName("System_Gain_AT_DCT_tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.System_Gain_AT_DCT_tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.System_Gain_AT_DCT_Config_Group = QtWidgets.QGroupBox(self.System_Gain_AT_DCT_tab)
        self.System_Gain_AT_DCT_Config_Group.setMaximumSize(QtCore.QSize(300, 16777215))
        self.System_Gain_AT_DCT_Config_Group.setObjectName("System_Gain_AT_DCT_Config_Group")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.System_Gain_AT_DCT_Config_Group)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.System_Gain_AT_DCT_StableVspd_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_StableVspd_lab.setMinimumSize(QtCore.QSize(100, 20))
        self.System_Gain_AT_DCT_StableVspd_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.System_Gain_AT_DCT_StableVspd_lab.setFont(font)
        self.System_Gain_AT_DCT_StableVspd_lab.setObjectName("System_Gain_AT_DCT_StableVspd_lab")
        self.gridLayout_13.addWidget(self.System_Gain_AT_DCT_StableVspd_lab, 2, 0, 1, 1)
        self.System_Gain_AT_DCT_Config_Lay = QtWidgets.QGridLayout()
        self.System_Gain_AT_DCT_Config_Lay.setObjectName("System_Gain_AT_DCT_Config_Lay")
        self.System_Gain_CVT = QtWidgets.QRadioButton(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_CVT.setObjectName("System_Gain_CVT")
        self.buttonGroup_PT_Type = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_PT_Type.setObjectName("buttonGroup_PT_Type")
        self.buttonGroup_PT_Type.addButton(self.System_Gain_CVT)
        self.System_Gain_AT_DCT_Config_Lay.addWidget(self.System_Gain_CVT, 1, 1, 1, 1)
        self.System_Gain_AT_DCT = QtWidgets.QRadioButton(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT.setChecked(True)
        self.System_Gain_AT_DCT.setObjectName("System_Gain_AT_DCT")
        self.buttonGroup_PT_Type.addButton(self.System_Gain_AT_DCT)
        self.System_Gain_AT_DCT_Config_Lay.addWidget(self.System_Gain_AT_DCT, 1, 0, 1, 1)
        self.System_Gain_AT_DCT_Features_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_Features_lab.setMinimumSize(QtCore.QSize(100, 30))
        self.System_Gain_AT_DCT_Features_lab.setMaximumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.System_Gain_AT_DCT_Features_lab.setFont(font)
        self.System_Gain_AT_DCT_Features_lab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.System_Gain_AT_DCT_Features_lab.setObjectName("System_Gain_AT_DCT_Features_lab")
        self.System_Gain_AT_DCT_Config_Lay.addWidget(self.System_Gain_AT_DCT_Features_lab, 2, 0, 1, 1)
        self.System_Gain_AT_DCT_Features_lab_2 = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_Features_lab_2.setMinimumSize(QtCore.QSize(100, 30))
        self.System_Gain_AT_DCT_Features_lab_2.setMaximumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.System_Gain_AT_DCT_Features_lab_2.setFont(font)
        self.System_Gain_AT_DCT_Features_lab_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.System_Gain_AT_DCT_Features_lab_2.setObjectName("System_Gain_AT_DCT_Features_lab_2")
        self.System_Gain_AT_DCT_Config_Lay.addWidget(self.System_Gain_AT_DCT_Features_lab_2, 0, 0, 1, 3)
        self.System_Gain_MT = QtWidgets.QRadioButton(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_MT.setObjectName("System_Gain_MT")
        self.buttonGroup_PT_Type.addButton(self.System_Gain_MT)
        self.System_Gain_AT_DCT_Config_Lay.addWidget(self.System_Gain_MT, 1, 2, 1, 1)
        self.System_Gain_AT_DCT_Index_comboBox = QtWidgets.QComboBox(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_Index_comboBox.setObjectName("System_Gain_AT_DCT_Index_comboBox")
        self.System_Gain_AT_DCT_Config_Lay.addWidget(self.System_Gain_AT_DCT_Index_comboBox, 2, 2, 1, 1)
        self.System_Gain_AT_DCT_Config_LayV = QtWidgets.QVBoxLayout()
        self.System_Gain_AT_DCT_Config_LayV.setObjectName("System_Gain_AT_DCT_Config_LayV")
        self.System_Gain_AT_DCT_Time_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_Time_lab.setMinimumSize(QtCore.QSize(100, 20))
        self.System_Gain_AT_DCT_Time_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Time_lab.setFont(font)
        self.System_Gain_AT_DCT_Time_lab.setObjectName("System_Gain_AT_DCT_Time_lab")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Time_lab)
        self.System_Gain_AT_DCT_Time = QtWidgets.QComboBox(self.System_Gain_AT_DCT_Config_Group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Time.setFont(font)
        self.System_Gain_AT_DCT_Time.setObjectName("System_Gain_AT_DCT_Time")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Time)
        self.System_Gain_AT_DCT_Vspd_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_Vspd_lab.setMinimumSize(QtCore.QSize(100, 20))
        self.System_Gain_AT_DCT_Vspd_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Vspd_lab.setFont(font)
        self.System_Gain_AT_DCT_Vspd_lab.setObjectName("System_Gain_AT_DCT_Vspd_lab")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Vspd_lab)
        self.System_Gain_AT_DCT_Vspd = QtWidgets.QComboBox(self.System_Gain_AT_DCT_Config_Group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Vspd.setFont(font)
        self.System_Gain_AT_DCT_Vspd.setObjectName("System_Gain_AT_DCT_Vspd")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Vspd)
        self.System_Gain_AT_DCT_Ped_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_Ped_lab.setMinimumSize(QtCore.QSize(100, 20))
        self.System_Gain_AT_DCT_Ped_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Ped_lab.setFont(font)
        self.System_Gain_AT_DCT_Ped_lab.setObjectName("System_Gain_AT_DCT_Ped_lab")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Ped_lab)
        self.System_Gain_AT_DCT_Ped = QtWidgets.QComboBox(self.System_Gain_AT_DCT_Config_Group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Ped.setFont(font)
        self.System_Gain_AT_DCT_Ped.setObjectName("System_Gain_AT_DCT_Ped")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Ped)
        self.System_Gain_AT_DCT_Acc_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_Acc_lab.setMinimumSize(QtCore.QSize(100, 20))
        self.System_Gain_AT_DCT_Acc_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Acc_lab.setFont(font)
        self.System_Gain_AT_DCT_Acc_lab.setObjectName("System_Gain_AT_DCT_Acc_lab")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Acc_lab)
        self.System_Gain_AT_DCT_Acc = QtWidgets.QComboBox(self.System_Gain_AT_DCT_Config_Group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Acc.setFont(font)
        self.System_Gain_AT_DCT_Acc.setObjectName("System_Gain_AT_DCT_Acc")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Acc)
        self.System_Gain_AT_DCT_Gear_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_Gear_lab.setMinimumSize(QtCore.QSize(100, 20))
        self.System_Gain_AT_DCT_Gear_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Gear_lab.setFont(font)
        self.System_Gain_AT_DCT_Gear_lab.setObjectName("System_Gain_AT_DCT_Gear_lab")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Gear_lab)
        self.System_Gain_AT_DCT_Gear = QtWidgets.QComboBox(self.System_Gain_AT_DCT_Config_Group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Gear.setFont(font)
        self.System_Gain_AT_DCT_Gear.setObjectName("System_Gain_AT_DCT_Gear")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Gear)
        self.System_Gain_AT_DCT_Toq_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_Toq_lab.setMinimumSize(QtCore.QSize(100, 20))
        self.System_Gain_AT_DCT_Toq_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Toq_lab.setFont(font)
        self.System_Gain_AT_DCT_Toq_lab.setObjectName("System_Gain_AT_DCT_Toq_lab")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Toq_lab)
        self.System_Gain_AT_DCT_Toq = QtWidgets.QComboBox(self.System_Gain_AT_DCT_Config_Group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Toq.setFont(font)
        self.System_Gain_AT_DCT_Toq.setObjectName("System_Gain_AT_DCT_Toq")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Toq)
        self.System_Gain_AT_DCT_Fuel_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_Fuel_lab.setMinimumSize(QtCore.QSize(100, 20))
        self.System_Gain_AT_DCT_Fuel_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Fuel_lab.setFont(font)
        self.System_Gain_AT_DCT_Fuel_lab.setObjectName("System_Gain_AT_DCT_Fuel_lab")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Fuel_lab)
        self.System_Gain_AT_DCT_Fuel = QtWidgets.QComboBox(self.System_Gain_AT_DCT_Config_Group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Fuel.setFont(font)
        self.System_Gain_AT_DCT_Fuel.setObjectName("System_Gain_AT_DCT_Fuel")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Fuel)
        self.System_Gain_AT_DCT_EnSpd_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_EnSpd_lab.setMinimumSize(QtCore.QSize(100, 20))
        self.System_Gain_AT_DCT_EnSpd_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.System_Gain_AT_DCT_EnSpd_lab.setFont(font)
        self.System_Gain_AT_DCT_EnSpd_lab.setObjectName("System_Gain_AT_DCT_EnSpd_lab")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_EnSpd_lab)
        self.System_Gain_AT_DCT_EnSpd = QtWidgets.QComboBox(self.System_Gain_AT_DCT_Config_Group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.System_Gain_AT_DCT_EnSpd.setFont(font)
        self.System_Gain_AT_DCT_EnSpd.setObjectName("System_Gain_AT_DCT_EnSpd")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_EnSpd)
        self.System_Gain_AT_DCT_TbSpd_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_TbSpd_lab.setMinimumSize(QtCore.QSize(100, 20))
        self.System_Gain_AT_DCT_TbSpd_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.System_Gain_AT_DCT_TbSpd_lab.setFont(font)
        self.System_Gain_AT_DCT_TbSpd_lab.setObjectName("System_Gain_AT_DCT_TbSpd_lab")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_TbSpd_lab)
        self.System_Gain_AT_DCT_TbSpd = QtWidgets.QComboBox(self.System_Gain_AT_DCT_Config_Group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.System_Gain_AT_DCT_TbSpd.setFont(font)
        self.System_Gain_AT_DCT_TbSpd.setObjectName("System_Gain_AT_DCT_TbSpd")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_TbSpd)
        self.System_Gain_AT_DCT_Config_Lay.addLayout(self.System_Gain_AT_DCT_Config_LayV, 3, 0, 1, 3)
        self.System_Gain_AT_DCT_New_Index = QtWidgets.QCheckBox(self.System_Gain_AT_DCT_Config_Group)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.System_Gain_AT_DCT_New_Index.setFont(font)
        self.System_Gain_AT_DCT_New_Index.setObjectName("System_Gain_AT_DCT_New_Index")
        self.System_Gain_AT_DCT_Config_Lay.addWidget(self.System_Gain_AT_DCT_New_Index, 2, 1, 1, 1)
        self.gridLayout_13.addLayout(self.System_Gain_AT_DCT_Config_Lay, 0, 0, 1, 4)
        self.System_Gain_AT_DCT_StablePed_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_StablePed_lab.setMinimumSize(QtCore.QSize(100, 20))
        self.System_Gain_AT_DCT_StablePed_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.System_Gain_AT_DCT_StablePed_lab.setFont(font)
        self.System_Gain_AT_DCT_StablePed_lab.setObjectName("System_Gain_AT_DCT_StablePed_lab")
        self.gridLayout_13.addWidget(self.System_Gain_AT_DCT_StablePed_lab, 3, 0, 1, 1)
        self.System_Gain_AT_DCT_AddInput = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_AddInput.setMinimumSize(QtCore.QSize(100, 30))
        self.System_Gain_AT_DCT_AddInput.setMaximumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.System_Gain_AT_DCT_AddInput.setFont(font)
        self.System_Gain_AT_DCT_AddInput.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.System_Gain_AT_DCT_AddInput.setObjectName("System_Gain_AT_DCT_AddInput")
        self.gridLayout_13.addWidget(self.System_Gain_AT_DCT_AddInput, 1, 0, 1, 2)
        self.SysGain_Cal = QtWidgets.QPushButton(self.System_Gain_AT_DCT_Config_Group)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.SysGain_Cal.setFont(font)
        self.SysGain_Cal.setStyleSheet("QPushButton{border-image: url(./Image/RunIcon.png);}\n"
"")
        self.SysGain_Cal.setObjectName("SysGain_Cal")
        self.gridLayout_13.addWidget(self.SysGain_Cal, 4, 0, 1, 4)
        self.Constant_Speed_Show_Speed_text = QtWidgets.QTextEdit(self.System_Gain_AT_DCT_Config_Group)
        self.Constant_Speed_Show_Speed_text.setMinimumSize(QtCore.QSize(0, 20))
        self.Constant_Speed_Show_Speed_text.setMaximumSize(QtCore.QSize(16777215, 60))
        self.Constant_Speed_Show_Speed_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Constant_Speed_Show_Speed_text.setObjectName("Constant_Speed_Show_Speed_text")
        self.gridLayout_13.addWidget(self.Constant_Speed_Show_Speed_text, 2, 1, 1, 3)
        self.Constant_Speed_Show_Ped_text = QtWidgets.QTextEdit(self.System_Gain_AT_DCT_Config_Group)
        self.Constant_Speed_Show_Ped_text.setMinimumSize(QtCore.QSize(0, 20))
        self.Constant_Speed_Show_Ped_text.setMaximumSize(QtCore.QSize(16777215, 60))
        self.Constant_Speed_Show_Ped_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Constant_Speed_Show_Ped_text.setObjectName("Constant_Speed_Show_Ped_text")
        self.gridLayout_13.addWidget(self.Constant_Speed_Show_Ped_text, 3, 1, 1, 3)
        self.Constant_Speed_Input_button = QtWidgets.QPushButton(self.System_Gain_AT_DCT_Config_Group)
        self.Constant_Speed_Input_button.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.Constant_Speed_Input_button.setFont(font)
        self.Constant_Speed_Input_button.setObjectName("Constant_Speed_Input_button")
        self.gridLayout_13.addWidget(self.Constant_Speed_Input_button, 1, 3, 1, 1)
        self.gridLayout_9.addWidget(self.System_Gain_AT_DCT_Config_Group, 0, 0, 2, 1)
        self.System_Gain_AT_DCT_Figs_Group = QtWidgets.QGroupBox(self.System_Gain_AT_DCT_tab)
        self.System_Gain_AT_DCT_Figs_Group.setObjectName("System_Gain_AT_DCT_Figs_Group")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.System_Gain_AT_DCT_Figs_Group)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.System_Gain_AT_DCT_Figs_scrollArea = QtWidgets.QScrollArea(self.System_Gain_AT_DCT_Figs_Group)
        self.System_Gain_AT_DCT_Figs_scrollArea.setWidgetResizable(True)
        self.System_Gain_AT_DCT_Figs_scrollArea.setObjectName("System_Gain_AT_DCT_Figs_scrollArea")
        self.System_Gain_AT_DCT_Figs_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.System_Gain_AT_DCT_Figs_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 625, 710))
        self.System_Gain_AT_DCT_Figs_scrollAreaWidgetContents.setObjectName("System_Gain_AT_DCT_Figs_scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.System_Gain_AT_DCT_Figs_scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.System_Gain_AT_DCT_Figs_scrollArea.setWidget(self.System_Gain_AT_DCT_Figs_scrollAreaWidgetContents)
        self.gridLayout_8.addWidget(self.System_Gain_AT_DCT_Figs_scrollArea, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.System_Gain_AT_DCT_Figs_Group, 0, 1, 1, 4)
        self.System_Gain_PT_Choose.addTab(self.System_Gain_AT_DCT_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.System_Gain_PT_Choose.addTab(self.tab, "")
        self.gridLayout_16.addWidget(self.System_Gain_PT_Choose, 0, 0, 1, 1)
        self.MainStackedWidget.addWidget(self.System_Gain_page)
        self.Cal_Result_page = QtWidgets.QWidget()
        self.Cal_Result_page.setObjectName("Cal_Result_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Cal_Result_page)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Cal_Result_tabWidget = QtWidgets.QTabWidget(self.Cal_Result_page)
        self.Cal_Result_tabWidget.setTabPosition(QtWidgets.QTabWidget.East)
        self.Cal_Result_tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.Cal_Result_tabWidget.setObjectName("Cal_Result_tabWidget")
        self.Cal_Result_acc_curve_tab = QtWidgets.QWidget()
        self.Cal_Result_acc_curve_tab.setObjectName("Cal_Result_acc_curve_tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Cal_Result_acc_curve_tab)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter_Cal_Result_acc_curve_tab = QtWidgets.QSplitter(self.Cal_Result_acc_curve_tab)
        self.splitter_Cal_Result_acc_curve_tab.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_Cal_Result_acc_curve_tab.setObjectName("splitter_Cal_Result_acc_curve_tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter_Cal_Result_acc_curve_tab)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Cal_Result_page_acc_curve_tabLayV = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Cal_Result_page_acc_curve_tabLayV.setContentsMargins(0, 0, 0, 0)
        self.Cal_Result_page_acc_curve_tabLayV.setSpacing(0)
        self.Cal_Result_page_acc_curve_tabLayV.setObjectName("Cal_Result_page_acc_curve_tabLayV")
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser.setMinimumSize(QtCore.QSize(500, 0))
        self.textBrowser.setObjectName("textBrowser")
        self.Cal_Result_page_acc_curve_tabLayV.addWidget(self.textBrowser)
        self.Cal_Result_acc_curve_tab_tableWidget = QtWidgets.QTableWidget(self.splitter_Cal_Result_acc_curve_tab)
        self.Cal_Result_acc_curve_tab_tableWidget.setObjectName("Cal_Result_acc_curve_tab_tableWidget")
        self.Cal_Result_acc_curve_tab_tableWidget.setColumnCount(5)
        self.Cal_Result_acc_curve_tab_tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.Cal_Result_acc_curve_tab_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Cal_Result_acc_curve_tab_tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Cal_Result_acc_curve_tab_tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Cal_Result_acc_curve_tab_tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Cal_Result_acc_curve_tab_tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Cal_Result_acc_curve_tab_tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Cal_Result_acc_curve_tab_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Cal_Result_acc_curve_tab_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Cal_Result_acc_curve_tab_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Cal_Result_acc_curve_tab_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Cal_Result_acc_curve_tab_tableWidget.setHorizontalHeaderItem(4, item)
        self.horizontalLayout_2.addWidget(self.splitter_Cal_Result_acc_curve_tab)
        self.Cal_Result_tabWidget.addTab(self.Cal_Result_acc_curve_tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Cal_Result_tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.Cal_Result_tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.Cal_Result_tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.Cal_Result_tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.Cal_Result_tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.Cal_Result_tabWidget.addTab(self.tab_7, "")
        self.verticalLayout_4.addWidget(self.Cal_Result_tabWidget)
        self.MainStackedWidget.addWidget(self.Cal_Result_page)
        self.Compare_Result_page = QtWidgets.QWidget()
        self.Compare_Result_page.setObjectName("Compare_Result_page")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.Compare_Result_page)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.History_Data_Choose = QtWidgets.QGroupBox(self.Compare_Result_page)
        self.History_Data_Choose.setMaximumSize(QtCore.QSize(16777215, 60))
        self.History_Data_Choose.setObjectName("History_Data_Choose")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.History_Data_Choose)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.History_Data_Choose_LayH = QtWidgets.QHBoxLayout()
        self.History_Data_Choose_LayH.setSpacing(3)
        self.History_Data_Choose_LayH.setObjectName("History_Data_Choose_LayH")
        self.History_Data_Choose_lab = QtWidgets.QLabel(self.History_Data_Choose)
        self.History_Data_Choose_lab.setMinimumSize(QtCore.QSize(130, 20))
        self.History_Data_Choose_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.History_Data_Choose_lab.setFont(font)
        self.History_Data_Choose_lab.setObjectName("History_Data_Choose_lab")
        self.History_Data_Choose_LayH.addWidget(self.History_Data_Choose_lab)
        self.History_Data_Choose_PlainTextEdit = QtWidgets.QPlainTextEdit(self.History_Data_Choose)
        self.History_Data_Choose_PlainTextEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.History_Data_Choose_PlainTextEdit.setMaximumSize(QtCore.QSize(16777215, 60))
        self.History_Data_Choose_PlainTextEdit.setObjectName("History_Data_Choose_PlainTextEdit")
        self.History_Data_Choose_LayH.addWidget(self.History_Data_Choose_PlainTextEdit)
        self.History_Data_Choose_PushButton = QtWidgets.QPushButton(self.History_Data_Choose)
        self.History_Data_Choose_PushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.History_Data_Choose_PushButton.setObjectName("History_Data_Choose_PushButton")
        self.History_Data_Choose_LayH.addWidget(self.History_Data_Choose_PushButton)
        self.gridLayout_10.addLayout(self.History_Data_Choose_LayH, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.History_Data_Choose, 0, 0, 1, 1)
        self.History_Data_Comp = QtWidgets.QGroupBox(self.Compare_Result_page)
        self.History_Data_Comp.setObjectName("History_Data_Comp")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.History_Data_Comp)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.History_Data_Comp_LayG = QtWidgets.QGridLayout()
        self.History_Data_Comp_LayG.setObjectName("History_Data_Comp_LayG")
        self.History_Data_Comp_scrollArea = QtWidgets.QScrollArea(self.History_Data_Comp)
        self.History_Data_Comp_scrollArea.setWidgetResizable(True)
        self.History_Data_Comp_scrollArea.setObjectName("History_Data_Comp_scrollArea")
        self.History_Data_Comp_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.History_Data_Comp_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 968, 666))
        self.History_Data_Comp_scrollAreaWidgetContents.setObjectName("History_Data_Comp_scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.History_Data_Comp_scrollAreaWidgetContents)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.History_Data_Comp_scrollArea.setWidget(self.History_Data_Comp_scrollAreaWidgetContents)
        self.History_Data_Comp_LayG.addWidget(self.History_Data_Comp_scrollArea, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.History_Data_Comp_LayG, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.History_Data_Comp, 1, 0, 1, 1)
        self.MainStackedWidget.addWidget(self.Compare_Result_page)
        self.Data_Base_page = QtWidgets.QWidget()
        self.Data_Base_page.setObjectName("Data_Base_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Data_Base_page)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Data_Base_table_label = QtWidgets.QLabel(self.Data_Base_page)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Data_Base_table_label.setFont(font)
        self.Data_Base_table_label.setObjectName("Data_Base_table_label")
        self.verticalLayout_2.addWidget(self.Data_Base_table_label)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit = QtWidgets.QLineEdit(self.Data_Base_page)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_6.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.Data_Base_page)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_6.addWidget(self.pushButton, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.Data_Base_page)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.Data_Base_page)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_6.addWidget(self.comboBox, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        self.Data_Base_tableWidget = QtWidgets.QTableWidget(self.Data_Base_page)
        self.Data_Base_tableWidget.setObjectName("Data_Base_tableWidget")
        self.Data_Base_tableWidget.setColumnCount(0)
        self.Data_Base_tableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.Data_Base_tableWidget)
        self.MainStackedWidget.addWidget(self.Data_Base_page)
        self.Cal_Setting_page = QtWidgets.QWidget()
        self.Cal_Setting_page.setObjectName("Cal_Setting_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Cal_Setting_page)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Cal_Setting_page_TabWidget = QtWidgets.QTabWidget(self.Cal_Setting_page)
        self.Cal_Setting_page_TabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.Cal_Setting_page_TabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.Cal_Setting_page_TabWidget.setObjectName("Cal_Setting_page_TabWidget")
        self.DataViewer_setting = QtWidgets.QWidget()
        self.DataViewer_setting.setObjectName("DataViewer_setting")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.DataViewer_setting)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.DataViewer_setting_Rawdata = QtWidgets.QGroupBox(self.DataViewer_setting)
        self.DataViewer_setting_Rawdata.setObjectName("DataViewer_setting_Rawdata")
        self.DataViewer_setting_Rawdata_mdf_HZ = QtWidgets.QLabel(self.DataViewer_setting_Rawdata)
        self.DataViewer_setting_Rawdata_mdf_HZ.setGeometry(QtCore.QRect(240, 40, 47, 13))
        self.DataViewer_setting_Rawdata_mdf_HZ.setObjectName("DataViewer_setting_Rawdata_mdf_HZ")
        self.DataViewer_setting_Rawdata_mdf_res_TE = QtWidgets.QTextEdit(self.DataViewer_setting_Rawdata)
        self.DataViewer_setting_Rawdata_mdf_res_TE.setGeometry(QtCore.QRect(130, 38, 104, 21))
        self.DataViewer_setting_Rawdata_mdf_res_TE.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DataViewer_setting_Rawdata_mdf_res_TE.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DataViewer_setting_Rawdata_mdf_res_TE.setObjectName("DataViewer_setting_Rawdata_mdf_res_TE")
        self.DataViewer_setting_Rawdata_mdf_res_HZ = QtWidgets.QLabel(self.DataViewer_setting_Rawdata)
        self.DataViewer_setting_Rawdata_mdf_res_HZ.setGeometry(QtCore.QRect(20, 40, 101, 16))
        self.DataViewer_setting_Rawdata_mdf_res_HZ.setObjectName("DataViewer_setting_Rawdata_mdf_res_HZ")
        self.verticalLayout_6.addWidget(self.DataViewer_setting_Rawdata)
        self.DataViewer_setting_Time_axis = QtWidgets.QGroupBox(self.DataViewer_setting)
        self.DataViewer_setting_Time_axis.setObjectName("DataViewer_setting_Time_axis")
        self.DataViewer_setting_Time_axis_Dots_RB = QtWidgets.QRadioButton(self.DataViewer_setting_Time_axis)
        self.DataViewer_setting_Time_axis_Dots_RB.setGeometry(QtCore.QRect(20, 30, 82, 17))
        self.DataViewer_setting_Time_axis_Dots_RB.setChecked(True)
        self.DataViewer_setting_Time_axis_Dots_RB.setObjectName("DataViewer_setting_Time_axis_Dots_RB")
        self.buttonGroup_DataViewer_TimeAxisSetting = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_DataViewer_TimeAxisSetting.setObjectName("buttonGroup_DataViewer_TimeAxisSetting")
        self.buttonGroup_DataViewer_TimeAxisSetting.addButton(self.DataViewer_setting_Time_axis_Dots_RB)
        self.DataViewer_setting_Time_axis_Samples_RB = QtWidgets.QRadioButton(self.DataViewer_setting_Time_axis)
        self.DataViewer_setting_Time_axis_Samples_RB.setGeometry(QtCore.QRect(120, 30, 82, 17))
        self.DataViewer_setting_Time_axis_Samples_RB.setObjectName("DataViewer_setting_Time_axis_Samples_RB")
        self.buttonGroup_DataViewer_TimeAxisSetting.addButton(self.DataViewer_setting_Time_axis_Samples_RB)
        self.DataViewer_setting_Time_axis_Signal_RB = QtWidgets.QRadioButton(self.DataViewer_setting_Time_axis)
        self.DataViewer_setting_Time_axis_Signal_RB.setGeometry(QtCore.QRect(260, 30, 82, 17))
        self.DataViewer_setting_Time_axis_Signal_RB.setObjectName("DataViewer_setting_Time_axis_Signal_RB")
        self.buttonGroup_DataViewer_TimeAxisSetting.addButton(self.DataViewer_setting_Time_axis_Signal_RB)
        self.DataViewer_setting_Time_axis_Samples_TE = QtWidgets.QTextEdit(self.DataViewer_setting_Time_axis)
        self.DataViewer_setting_Time_axis_Samples_TE.setGeometry(QtCore.QRect(120, 60, 104, 21))
        self.DataViewer_setting_Time_axis_Samples_TE.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DataViewer_setting_Time_axis_Samples_TE.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DataViewer_setting_Time_axis_Samples_TE.setObjectName("DataViewer_setting_Time_axis_Samples_TE")
        self.DataViewer_setting_Time_axis_Samples_comboBox = QtWidgets.QComboBox(self.DataViewer_setting_Time_axis)
        self.DataViewer_setting_Time_axis_Samples_comboBox.setGeometry(QtCore.QRect(260, 60, 121, 22))
        self.DataViewer_setting_Time_axis_Samples_comboBox.setObjectName("DataViewer_setting_Time_axis_Samples_comboBox")
        self.DataViewer_setting_Time_axis_Samples_HZ = QtWidgets.QLabel(self.DataViewer_setting_Time_axis)
        self.DataViewer_setting_Time_axis_Samples_HZ.setGeometry(QtCore.QRect(230, 62, 47, 13))
        self.DataViewer_setting_Time_axis_Samples_HZ.setObjectName("DataViewer_setting_Time_axis_Samples_HZ")
        self.verticalLayout_6.addWidget(self.DataViewer_setting_Time_axis)
        self.groupBox_2 = QtWidgets.QGroupBox(self.DataViewer_setting)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.Cal_Setting_page_TabWidget.addTab(self.DataViewer_setting, "")
        self.SystemGain_setting = QtWidgets.QWidget()
        self.SystemGain_setting.setObjectName("SystemGain_setting")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.SystemGain_setting)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.SystemGain_Cal_setting = QtWidgets.QGroupBox(self.SystemGain_setting)
        self.SystemGain_Cal_setting.setObjectName("SystemGain_Cal_setting")
        self.verticalLayout_7.addWidget(self.SystemGain_Cal_setting)
        self.Constant_Speed_setting = QtWidgets.QGroupBox(self.SystemGain_setting)
        self.Constant_Speed_setting.setObjectName("Constant_Speed_setting")
        self.Constant_Speed_features_follow_RB = QtWidgets.QRadioButton(self.Constant_Speed_setting)
        self.Constant_Speed_features_follow_RB.setGeometry(QtCore.QRect(30, 90, 121, 17))
        self.Constant_Speed_features_follow_RB.setChecked(True)
        self.Constant_Speed_features_follow_RB.setObjectName("Constant_Speed_features_follow_RB")
        self.buttonGroup_Cons_Speed_Feature_Rule = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_Cons_Speed_Feature_Rule.setObjectName("buttonGroup_Cons_Speed_Feature_Rule")
        self.buttonGroup_Cons_Speed_Feature_Rule.addButton(self.Constant_Speed_features_follow_RB)
        self.Constant_Speed_features_reslect_RB = QtWidgets.QRadioButton(self.Constant_Speed_setting)
        self.Constant_Speed_features_reslect_RB.setGeometry(QtCore.QRect(190, 90, 141, 17))
        self.Constant_Speed_features_reslect_RB.setObjectName("Constant_Speed_features_reslect_RB")
        self.buttonGroup_Cons_Speed_Feature_Rule.addButton(self.Constant_Speed_features_reslect_RB)
        self.Constant_Speed_frequency_text = QtWidgets.QTextEdit(self.Constant_Speed_setting)
        self.Constant_Speed_frequency_text.setGeometry(QtCore.QRect(80, 40, 91, 21))
        self.Constant_Speed_frequency_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Constant_Speed_frequency_text.setObjectName("Constant_Speed_frequency_text")
        self.Constant_Speed_frequency_lab = QtWidgets.QLabel(self.Constant_Speed_setting)
        self.Constant_Speed_frequency_lab.setGeometry(QtCore.QRect(30, 40, 47, 13))
        self.Constant_Speed_frequency_lab.setObjectName("Constant_Speed_frequency_lab")
        self.verticalLayout_7.addWidget(self.Constant_Speed_setting)
        self.Cal_Setting_page_TabWidget.addTab(self.SystemGain_setting, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.Cal_Setting_page_TabWidget.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.Cal_Setting_page_TabWidget.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.Cal_Setting_page_TabWidget.addTab(self.tab_12, "")
        self.verticalLayout_5.addWidget(self.Cal_Setting_page_TabWidget)
        self.MainStackedWidget.addWidget(self.Cal_Setting_page)
        self.InfoWidget = QtWidgets.QListWidget(self.splitter_centralwidget)
        self.InfoWidget.setObjectName("InfoWidget")
        self.gridLayout_3.addWidget(self.splitter_centralwidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1010, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(32, 24))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actiontest = QtWidgets.QAction(MainWindow)
        self.actiontest.setObjectName("actiontest")
        self.actiontest2 = QtWidgets.QAction(MainWindow)
        self.actiontest2.setObjectName("actiontest2")
        self.menu_Engine_Working_Dist = QtWidgets.QAction(MainWindow)
        self.menu_Engine_Working_Dist.setObjectName("menu_Engine_Working_Dist")
        self.menu_InputData = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.menu_InputData.setFont(font)
        self.menu_InputData.setObjectName("menu_InputData")
        self.menu_CalData = QtWidgets.QAction(MainWindow)
        self.menu_CalData.setObjectName("menu_CalData")
        self.menu_Exit = QtWidgets.QAction(MainWindow)
        self.menu_Exit.setObjectName("menu_Exit")
        self.menu_Guildlines = QtWidgets.QAction(MainWindow)
        self.menu_Guildlines.setObjectName("menu_Guildlines")
        self.menu_ContactUs = QtWidgets.QAction(MainWindow)
        self.menu_ContactUs.setObjectName("menu_ContactUs")
        self.menu_Shifting_Strategy = QtWidgets.QAction(MainWindow)
        self.menu_Shifting_Strategy.setObjectName("menu_Shifting_Strategy")
        self.menu_Speed_Dist = QtWidgets.QAction(MainWindow)
        self.menu_Speed_Dist.setObjectName("menu_Speed_Dist")
        self.action_Data_Viewer = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Image/Icon/find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Data_Viewer.setIcon(icon1)
        self.action_Data_Viewer.setObjectName("action_Data_Viewer")
        self.action_System_Gain = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Image/Icon/wave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_System_Gain.setIcon(icon2)
        self.action_System_Gain.setObjectName("action_System_Gain")
        self.action_Compare_Result = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Image/Icon/compare01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Compare_Result.setIcon(icon3)
        self.action_Compare_Result.setObjectName("action_Compare_Result")
        self.menu_Save = QtWidgets.QAction(MainWindow)
        self.menu_Save.setObjectName("menu_Save")
        self.menu_Output_Report = QtWidgets.QAction(MainWindow)
        self.menu_Output_Report.setObjectName("menu_Output_Report")
        self.action_Cal_Setting = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Image/Icon/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Cal_Setting.setIcon(icon4)
        self.action_Cal_Setting.setObjectName("action_Cal_Setting")
        self.action_Data_Base = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Image/Icon/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Data_Base.setIcon(icon5)
        self.action_Data_Base.setObjectName("action_Data_Base")
        self.action_Cal_Result = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Image/Icon/result.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Cal_Result.setIcon(icon6)
        self.action_Cal_Result.setObjectName("action_Cal_Result")
        self.menu.addAction(self.menu_InputData)
        self.menu.addAction(self.menu_Save)
        self.menu.addAction(self.menu_Output_Report)
        self.menu.addSeparator()
        self.menu.addAction(self.menu_Exit)
        self.menu_2.addAction(self.menu_Guildlines)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.menu_ContactUs)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.toolBar.addAction(self.action_Data_Viewer)
        self.toolBar.addAction(self.action_System_Gain)
        self.toolBar.addAction(self.action_Cal_Result)
        self.toolBar.addAction(self.action_Compare_Result)
        self.toolBar.addAction(self.action_Data_Base)
        self.toolBar.addAction(self.action_Cal_Setting)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.MainStackedWidget.setCurrentIndex(0)
        self.System_Gain_PT_Choose.setCurrentIndex(0)
        self.Cal_Result_tabWidget.setCurrentIndex(0)
        self.Cal_Setting_page_TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.System_Gain_AT_DCT_Vspd, self.System_Gain_AT_DCT_Ped)
        MainWindow.setTabOrder(self.System_Gain_AT_DCT_Ped, self.System_Gain_AT_DCT_Acc)
        MainWindow.setTabOrder(self.System_Gain_AT_DCT_Acc, self.System_Gain_AT_DCT_Gear)
        MainWindow.setTabOrder(self.System_Gain_AT_DCT_Gear, self.System_Gain_AT_DCT_Toq)
        MainWindow.setTabOrder(self.System_Gain_AT_DCT_Toq, self.System_Gain_AT_DCT_Fuel)
        MainWindow.setTabOrder(self.System_Gain_AT_DCT_Fuel, self.System_Gain_AT_DCT_EnSpd)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SystemGainSolver V1.0.0"))
        self.Data_Viewer_CheckBox_groupBox.setTitle(_translate("MainWindow", "信号选取"))
        self.System_Gain_AT_DCT_Config_Group.setTitle(_translate("MainWindow", "配置"))
        self.System_Gain_AT_DCT_StableVspd_lab.setText(_translate("MainWindow", "稳态车速："))
        self.System_Gain_CVT.setText(_translate("MainWindow", "CVT"))
        self.System_Gain_AT_DCT.setText(_translate("MainWindow", "AT/DCT"))
        self.System_Gain_AT_DCT_Features_lab.setText(_translate("MainWindow", "字段选择："))
        self.System_Gain_AT_DCT_Features_lab_2.setText(_translate("MainWindow", "动力总成："))
        self.System_Gain_MT.setText(_translate("MainWindow", "MT"))
        self.System_Gain_AT_DCT_Time_lab.setText(_translate("MainWindow", "时间(s)"))
        self.System_Gain_AT_DCT_Vspd_lab.setText(_translate("MainWindow", "车速(km/h)"))
        self.System_Gain_AT_DCT_Ped_lab.setText(_translate("MainWindow", "油门(-)"))
        self.System_Gain_AT_DCT_Acc_lab.setText(_translate("MainWindow", "加速度(g)"))
        self.System_Gain_AT_DCT_Gear_lab.setText(_translate("MainWindow", "档位(-)"))
        self.System_Gain_AT_DCT_Toq_lab.setText(_translate("MainWindow", "扭矩(N.m)"))
        self.System_Gain_AT_DCT_Fuel_lab.setText(_translate("MainWindow", "喷油量(ul/s)"))
        self.System_Gain_AT_DCT_EnSpd_lab.setText(_translate("MainWindow", "发动机转速(rpm)"))
        self.System_Gain_AT_DCT_TbSpd_lab.setText(_translate("MainWindow", "涡轮转速(rpm)"))
        self.System_Gain_AT_DCT_New_Index.setText(_translate("MainWindow", "新建索引"))
        self.System_Gain_AT_DCT_StablePed_lab.setText(_translate("MainWindow", "踏板信号："))
        self.System_Gain_AT_DCT_AddInput.setText(_translate("MainWindow", "附加输入："))
        self.SysGain_Cal.setText(_translate("MainWindow", "计       算"))
        self.Constant_Speed_Show_Speed_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-----</p></body></html>"))
        self.Constant_Speed_Show_Ped_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-----</p></body></html>"))
        self.Constant_Speed_Input_button.setText(_translate("MainWindow", "导入"))
        self.System_Gain_AT_DCT_Figs_Group.setTitle(_translate("MainWindow", "输出图片"))
        self.System_Gain_PT_Choose.setTabText(self.System_Gain_PT_Choose.indexOf(self.System_Gain_AT_DCT_tab), _translate("MainWindow", "Calculation"))
        self.System_Gain_PT_Choose.setTabText(self.System_Gain_PT_Choose.indexOf(self.tab), _translate("MainWindow", "Rating"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:26pt; font-weight:600;\">待建设</span></p></body></html>"))
        item = self.Cal_Result_acc_curve_tab_tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.Cal_Result_acc_curve_tab_tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.Cal_Result_acc_curve_tab_tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.Cal_Result_acc_curve_tab_tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.Cal_Result_acc_curve_tab_tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.Cal_Result_acc_curve_tab_tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.Cal_Result_acc_curve_tab_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "新建列"))
        item = self.Cal_Result_acc_curve_tab_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "新建列"))
        item = self.Cal_Result_acc_curve_tab_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "新建列"))
        item = self.Cal_Result_acc_curve_tab_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "新建列"))
        item = self.Cal_Result_acc_curve_tab_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "新建列"))
        self.Cal_Result_tabWidget.setTabText(self.Cal_Result_tabWidget.indexOf(self.Cal_Result_acc_curve_tab), _translate("MainWindow", "Acc Curve"))
        self.Cal_Result_tabWidget.setTabText(self.Cal_Result_tabWidget.indexOf(self.tab_2), _translate("MainWindow", "System Gain Curve"))
        self.Cal_Result_tabWidget.setTabText(self.Cal_Result_tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Cons Speed"))
        self.Cal_Result_tabWidget.setTabText(self.Cal_Result_tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Shift Map"))
        self.Cal_Result_tabWidget.setTabText(self.Cal_Result_tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Launch"))
        self.Cal_Result_tabWidget.setTabText(self.Cal_Result_tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Pedal Map"))
        self.Cal_Result_tabWidget.setTabText(self.Cal_Result_tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Max Acc"))
        self.History_Data_Choose.setTitle(_translate("MainWindow", "计算结果导入"))
        self.History_Data_Choose_lab.setText(_translate("MainWindow", "历史测试数据导入："))
        self.History_Data_Choose_PushButton.setText(_translate("MainWindow", "对比"))
        self.History_Data_Comp.setTitle(_translate("MainWindow", "对比图"))
        self.Data_Base_table_label.setText(_translate("MainWindow", "数据库页面"))
        self.pushButton.setText(_translate("MainWindow", "查询"))
        self.label.setText(_translate("MainWindow", "查询条件："))
        self.DataViewer_setting_Rawdata.setTitle(_translate("MainWindow", "数据源"))
        self.DataViewer_setting_Rawdata_mdf_HZ.setText(_translate("MainWindow", "HZ"))
        self.DataViewer_setting_Rawdata_mdf_res_TE.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">20</p></body></html>"))
        self.DataViewer_setting_Rawdata_mdf_res_HZ.setText(_translate("MainWindow", ".dat/.mdf 重采样率"))
        self.DataViewer_setting_Time_axis.setTitle(_translate("MainWindow", "时间轴设置"))
        self.DataViewer_setting_Time_axis_Dots_RB.setText(_translate("MainWindow", "点数基准"))
        self.DataViewer_setting_Time_axis_Samples_RB.setText(_translate("MainWindow", "采样率基准"))
        self.DataViewer_setting_Time_axis_Signal_RB.setText(_translate("MainWindow", "自定义信号"))
        self.DataViewer_setting_Time_axis_Samples_TE.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">20</p></body></html>"))
        self.DataViewer_setting_Time_axis_Samples_HZ.setText(_translate("MainWindow", "HZ"))
        self.groupBox_2.setTitle(_translate("MainWindow", "坐标轴设置"))
        self.Cal_Setting_page_TabWidget.setTabText(self.Cal_Setting_page_TabWidget.indexOf(self.DataViewer_setting), _translate("MainWindow", "DataViewer"))
        self.SystemGain_Cal_setting.setTitle(_translate("MainWindow", "SG计算参数规则"))
        self.Constant_Speed_setting.setTitle(_translate("MainWindow", "稳态车速导入原则"))
        self.Constant_Speed_features_follow_RB.setText(_translate("MainWindow", "沿用SG信号选取规则"))
        self.Constant_Speed_features_reslect_RB.setText(_translate("MainWindow", "自定义选取"))
        self.Constant_Speed_frequency_lab.setText(_translate("MainWindow", "采样率："))
        self.Cal_Setting_page_TabWidget.setTabText(self.Cal_Setting_page_TabWidget.indexOf(self.SystemGain_setting), _translate("MainWindow", "SystemGain"))
        self.Cal_Setting_page_TabWidget.setTabText(self.Cal_Setting_page_TabWidget.indexOf(self.tab_10), _translate("MainWindow", "CalResult"))
        self.Cal_Setting_page_TabWidget.setTabText(self.Cal_Setting_page_TabWidget.indexOf(self.tab_11), _translate("MainWindow", "CompareResult"))
        self.Cal_Setting_page_TabWidget.setTabText(self.Cal_Setting_page_TabWidget.indexOf(self.tab_12), _translate("MainWindow", "DataBase"))
        self.menu.setTitle(_translate("MainWindow", "文件 (File)"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助 (Help)"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actiontest.setText(_translate("MainWindow", "test"))
        self.actiontest2.setText(_translate("MainWindow", "test2"))
        self.menu_Engine_Working_Dist.setText(_translate("MainWindow", "发动机工况点分布 Engine Work Point Dist."))
        self.menu_InputData.setText(_translate("MainWindow", "导入测试数据 Input Test Data"))
        self.menu_CalData.setText(_translate("MainWindow", "求解 Solution"))
        self.menu_Exit.setText(_translate("MainWindow", "退出 Exit"))
        self.menu_Guildlines.setText(_translate("MainWindow", "操作指南 Guildlines"))
        self.menu_ContactUs.setText(_translate("MainWindow", "联系作者 Contact Us!"))
        self.menu_Shifting_Strategy.setText(_translate("MainWindow", "换挡策略分布 Shifting Strategy Dist."))
        self.menu_Speed_Dist.setText(_translate("MainWindow", "速度分布 Speed Dist."))
        self.action_Data_Viewer.setText(_translate("MainWindow", "Data Viewer"))
        self.action_Data_Viewer.setToolTip(_translate("MainWindow", "Data_Viewer"))
        self.action_Data_Viewer.setShortcut(_translate("MainWindow", "F1"))
        self.action_System_Gain.setText(_translate("MainWindow", "System Gain"))
        self.action_System_Gain.setToolTip(_translate("MainWindow", "System_Gain"))
        self.action_System_Gain.setShortcut(_translate("MainWindow", "F2"))
        self.action_Compare_Result.setText(_translate("MainWindow", "Compare Result"))
        self.action_Compare_Result.setToolTip(_translate("MainWindow", "Compare_Result"))
        self.action_Compare_Result.setShortcut(_translate("MainWindow", "F3"))
        self.menu_Save.setText(_translate("MainWindow", "保存计算结果 Save Data"))
        self.menu_Output_Report.setText(_translate("MainWindow", "导出计算报告 Output Report"))
        self.action_Cal_Setting.setText(_translate("MainWindow", "Cal Settings"))
        self.action_Data_Base.setText(_translate("MainWindow", "Data Base"))
        self.action_Cal_Result.setText(_translate("MainWindow", "Cal Result"))


