# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SystemGainUi.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import Icon

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1011, 902)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter_centralwidget = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_centralwidget.setOrientation(QtCore.Qt.Vertical)
        self.splitter_centralwidget.setObjectName("splitter_centralwidget")
        self.MainStackedWidget = QtWidgets.QStackedWidget(self.splitter_centralwidget)
        self.MainStackedWidget.setObjectName("MainStackedWidget")
        self.Data_Viewer_page = QtWidgets.QWidget()
        self.Data_Viewer_page.setObjectName("Data_Viewer_page")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Data_Viewer_page)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_Data_Viewer_page = QtWidgets.QSplitter(self.Data_Viewer_page)
        self.splitter_Data_Viewer_page.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_Data_Viewer_page.setObjectName("splitter_Data_Viewer_page")
        self.Data_Viewer_CheckBox_scrollArea = QtWidgets.QScrollArea(self.splitter_Data_Viewer_page)
        self.Data_Viewer_CheckBox_scrollArea.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.Data_Viewer_CheckBox_scrollArea.setWidgetResizable(True)
        self.Data_Viewer_CheckBox_scrollArea.setObjectName("Data_Viewer_CheckBox_scrollArea")
        self.Data_Viewer_CheckBox_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.Data_Viewer_CheckBox_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 356, 712))
        self.Data_Viewer_CheckBox_scrollAreaWidgetContents.setObjectName("Data_Viewer_CheckBox_scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.Data_Viewer_CheckBox_scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Data_Viewer_CheckBox_groupBox = QtWidgets.QGroupBox(self.Data_Viewer_CheckBox_scrollAreaWidgetContents)
        self.Data_Viewer_CheckBox_groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Data_Viewer_CheckBox_groupBox.setObjectName("Data_Viewer_CheckBox_groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Data_Viewer_CheckBox_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Infolabel = QtWidgets.QLabel(self.Data_Viewer_CheckBox_groupBox)
        self.Infolabel.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Infolabel.setFont(font)
        self.Infolabel.setObjectName("Infolabel")
        self.verticalLayout.addWidget(self.Infolabel)
        self.gridLayout.addWidget(self.Data_Viewer_CheckBox_groupBox, 0, 0, 1, 1)
        self.Data_Viewer_CheckBox_scrollArea.setWidget(self.Data_Viewer_CheckBox_scrollAreaWidgetContents)
        self.widget = QtWidgets.QWidget(self.splitter_Data_Viewer_page)
        self.widget.setObjectName("widget")
        self.Data_Viewer_page_graphicsView_LayV = QtWidgets.QVBoxLayout(self.widget)
        self.Data_Viewer_page_graphicsView_LayV.setContentsMargins(0, 0, 0, 0)
        self.Data_Viewer_page_graphicsView_LayV.setObjectName("Data_Viewer_page_graphicsView_LayV")
        self.horizontalLayout.addWidget(self.splitter_Data_Viewer_page)
        self.MainStackedWidget.addWidget(self.Data_Viewer_page)
        self.System_Gain_page = QtWidgets.QWidget()
        self.System_Gain_page.setObjectName("System_Gain_page")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.System_Gain_page)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.System_Gain_PT_Choose = QtWidgets.QTabWidget(self.System_Gain_page)
        self.System_Gain_PT_Choose.setTabPosition(QtWidgets.QTabWidget.West)
        self.System_Gain_PT_Choose.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.System_Gain_PT_Choose.setObjectName("System_Gain_PT_Choose")
        self.System_Gain_AT_DCT_tab = QtWidgets.QWidget()
        self.System_Gain_AT_DCT_tab.setObjectName("System_Gain_AT_DCT_tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.System_Gain_AT_DCT_tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.System_Gain_AT_DCT_Config_Group = QtWidgets.QGroupBox(self.System_Gain_AT_DCT_tab)
        self.System_Gain_AT_DCT_Config_Group.setMaximumSize(QtCore.QSize(300, 16777215))
        self.System_Gain_AT_DCT_Config_Group.setObjectName("System_Gain_AT_DCT_Config_Group")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.System_Gain_AT_DCT_Config_Group)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.System_Gain_AT_DCT_Config_Lay = QtWidgets.QGridLayout()
        self.System_Gain_AT_DCT_Config_Lay.setObjectName("System_Gain_AT_DCT_Config_Lay")
        self.System_Gain_AT_DCT_Config_LayV = QtWidgets.QVBoxLayout()
        self.System_Gain_AT_DCT_Config_LayV.setObjectName("System_Gain_AT_DCT_Config_LayV")
        self.System_Gain_AT_DCT_Features_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_Features_lab.setMinimumSize(QtCore.QSize(100, 30))
        self.System_Gain_AT_DCT_Features_lab.setMaximumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.System_Gain_AT_DCT_Features_lab.setFont(font)
        self.System_Gain_AT_DCT_Features_lab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.System_Gain_AT_DCT_Features_lab.setObjectName("System_Gain_AT_DCT_Features_lab")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Features_lab)
        self.System_Gain_AT_DCT_Time_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_Time_lab.setMinimumSize(QtCore.QSize(100, 20))
        self.System_Gain_AT_DCT_Time_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Time_lab.setFont(font)
        self.System_Gain_AT_DCT_Time_lab.setObjectName("System_Gain_AT_DCT_Time_lab")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Time_lab)
        self.System_Gain_AT_DCT_Time = QtWidgets.QComboBox(self.System_Gain_AT_DCT_Config_Group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Time.setFont(font)
        self.System_Gain_AT_DCT_Time.setObjectName("System_Gain_AT_DCT_Time")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Time)
        self.System_Gain_AT_DCT_Vspd_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_Vspd_lab.setMinimumSize(QtCore.QSize(100, 20))
        self.System_Gain_AT_DCT_Vspd_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Vspd_lab.setFont(font)
        self.System_Gain_AT_DCT_Vspd_lab.setObjectName("System_Gain_AT_DCT_Vspd_lab")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Vspd_lab)
        self.System_Gain_AT_DCT_Vspd = QtWidgets.QComboBox(self.System_Gain_AT_DCT_Config_Group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Vspd.setFont(font)
        self.System_Gain_AT_DCT_Vspd.setObjectName("System_Gain_AT_DCT_Vspd")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Vspd)
        self.System_Gain_AT_DCT_Ped_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_Ped_lab.setMinimumSize(QtCore.QSize(100, 20))
        self.System_Gain_AT_DCT_Ped_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Ped_lab.setFont(font)
        self.System_Gain_AT_DCT_Ped_lab.setObjectName("System_Gain_AT_DCT_Ped_lab")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Ped_lab)
        self.System_Gain_AT_DCT_Ped = QtWidgets.QComboBox(self.System_Gain_AT_DCT_Config_Group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Ped.setFont(font)
        self.System_Gain_AT_DCT_Ped.setObjectName("System_Gain_AT_DCT_Ped")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Ped)
        self.System_Gain_AT_DCT_Acc_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_Acc_lab.setMinimumSize(QtCore.QSize(100, 20))
        self.System_Gain_AT_DCT_Acc_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Acc_lab.setFont(font)
        self.System_Gain_AT_DCT_Acc_lab.setObjectName("System_Gain_AT_DCT_Acc_lab")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Acc_lab)
        self.System_Gain_AT_DCT_Acc = QtWidgets.QComboBox(self.System_Gain_AT_DCT_Config_Group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Acc.setFont(font)
        self.System_Gain_AT_DCT_Acc.setObjectName("System_Gain_AT_DCT_Acc")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Acc)
        self.System_Gain_AT_DCT_Gear_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_Gear_lab.setMinimumSize(QtCore.QSize(100, 20))
        self.System_Gain_AT_DCT_Gear_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Gear_lab.setFont(font)
        self.System_Gain_AT_DCT_Gear_lab.setObjectName("System_Gain_AT_DCT_Gear_lab")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Gear_lab)
        self.System_Gain_AT_DCT_Gear = QtWidgets.QComboBox(self.System_Gain_AT_DCT_Config_Group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Gear.setFont(font)
        self.System_Gain_AT_DCT_Gear.setObjectName("System_Gain_AT_DCT_Gear")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Gear)
        self.System_Gain_AT_DCT_Toq_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_Toq_lab.setMinimumSize(QtCore.QSize(100, 20))
        self.System_Gain_AT_DCT_Toq_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Toq_lab.setFont(font)
        self.System_Gain_AT_DCT_Toq_lab.setObjectName("System_Gain_AT_DCT_Toq_lab")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Toq_lab)
        self.System_Gain_AT_DCT_Toq = QtWidgets.QComboBox(self.System_Gain_AT_DCT_Config_Group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Toq.setFont(font)
        self.System_Gain_AT_DCT_Toq.setObjectName("System_Gain_AT_DCT_Toq")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Toq)
        self.System_Gain_AT_DCT_Fuel_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_Fuel_lab.setMinimumSize(QtCore.QSize(100, 20))
        self.System_Gain_AT_DCT_Fuel_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Fuel_lab.setFont(font)
        self.System_Gain_AT_DCT_Fuel_lab.setObjectName("System_Gain_AT_DCT_Fuel_lab")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Fuel_lab)
        self.System_Gain_AT_DCT_Fuel = QtWidgets.QComboBox(self.System_Gain_AT_DCT_Config_Group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.System_Gain_AT_DCT_Fuel.setFont(font)
        self.System_Gain_AT_DCT_Fuel.setObjectName("System_Gain_AT_DCT_Fuel")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_Fuel)
        self.System_Gain_AT_DCT_EnSpd_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_EnSpd_lab.setMinimumSize(QtCore.QSize(100, 20))
        self.System_Gain_AT_DCT_EnSpd_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.System_Gain_AT_DCT_EnSpd_lab.setFont(font)
        self.System_Gain_AT_DCT_EnSpd_lab.setObjectName("System_Gain_AT_DCT_EnSpd_lab")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_EnSpd_lab)
        self.System_Gain_AT_DCT_EnSpd = QtWidgets.QComboBox(self.System_Gain_AT_DCT_Config_Group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.System_Gain_AT_DCT_EnSpd.setFont(font)
        self.System_Gain_AT_DCT_EnSpd.setObjectName("System_Gain_AT_DCT_EnSpd")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_EnSpd)
        self.System_Gain_AT_DCT_TbSpd_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_TbSpd_lab.setMinimumSize(QtCore.QSize(100, 20))
        self.System_Gain_AT_DCT_TbSpd_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.System_Gain_AT_DCT_TbSpd_lab.setFont(font)
        self.System_Gain_AT_DCT_TbSpd_lab.setObjectName("System_Gain_AT_DCT_TbSpd_lab")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_TbSpd_lab)
        self.System_Gain_AT_DCT_TbSpd = QtWidgets.QComboBox(self.System_Gain_AT_DCT_Config_Group)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.System_Gain_AT_DCT_TbSpd.setFont(font)
        self.System_Gain_AT_DCT_TbSpd.setObjectName("System_Gain_AT_DCT_TbSpd")
        self.System_Gain_AT_DCT_Config_LayV.addWidget(self.System_Gain_AT_DCT_TbSpd)
        self.System_Gain_AT_DCT_Config_Lay.addLayout(self.System_Gain_AT_DCT_Config_LayV, 1, 0, 1, 1)
        self.gridLayout_13.addLayout(self.System_Gain_AT_DCT_Config_Lay, 0, 0, 1, 2)
        self.System_Gain_AT_DCT_AddInput = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_AddInput.setMinimumSize(QtCore.QSize(100, 30))
        self.System_Gain_AT_DCT_AddInput.setMaximumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.System_Gain_AT_DCT_AddInput.setFont(font)
        self.System_Gain_AT_DCT_AddInput.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.System_Gain_AT_DCT_AddInput.setObjectName("System_Gain_AT_DCT_AddInput")
        self.gridLayout_13.addWidget(self.System_Gain_AT_DCT_AddInput, 1, 0, 1, 2)
        self.System_Gain_AT_DCT_StableVspd_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_StableVspd_lab.setMinimumSize(QtCore.QSize(100, 20))
        self.System_Gain_AT_DCT_StableVspd_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.System_Gain_AT_DCT_StableVspd_lab.setFont(font)
        self.System_Gain_AT_DCT_StableVspd_lab.setObjectName("System_Gain_AT_DCT_StableVspd_lab")
        self.gridLayout_13.addWidget(self.System_Gain_AT_DCT_StableVspd_lab, 2, 0, 1, 1)
        self.System_Gain_AT_DCT_StableVspd_TextEdit = QtWidgets.QTextEdit(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_StableVspd_TextEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.System_Gain_AT_DCT_StableVspd_TextEdit.setMaximumSize(QtCore.QSize(16777215, 60))
        self.System_Gain_AT_DCT_StableVspd_TextEdit.setObjectName("System_Gain_AT_DCT_StableVspd_TextEdit")
        self.gridLayout_13.addWidget(self.System_Gain_AT_DCT_StableVspd_TextEdit, 2, 1, 1, 1)
        self.System_Gain_AT_DCT_StablePed_lab = QtWidgets.QLabel(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_StablePed_lab.setMinimumSize(QtCore.QSize(100, 20))
        self.System_Gain_AT_DCT_StablePed_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.System_Gain_AT_DCT_StablePed_lab.setFont(font)
        self.System_Gain_AT_DCT_StablePed_lab.setObjectName("System_Gain_AT_DCT_StablePed_lab")
        self.gridLayout_13.addWidget(self.System_Gain_AT_DCT_StablePed_lab, 3, 0, 1, 1)
        self.System_Gain_AT_DCT_StablePed_TextEdit = QtWidgets.QTextEdit(self.System_Gain_AT_DCT_Config_Group)
        self.System_Gain_AT_DCT_StablePed_TextEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.System_Gain_AT_DCT_StablePed_TextEdit.setMaximumSize(QtCore.QSize(16777215, 60))
        self.System_Gain_AT_DCT_StablePed_TextEdit.setObjectName("System_Gain_AT_DCT_StablePed_TextEdit")
        self.gridLayout_13.addWidget(self.System_Gain_AT_DCT_StablePed_TextEdit, 3, 1, 1, 1)
        self.SysGain_Cal = QtWidgets.QPushButton(self.System_Gain_AT_DCT_Config_Group)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(18)
        self.SysGain_Cal.setFont(font)
        self.SysGain_Cal.setStyleSheet("QPushButton{border-image: url(./Image/RunIcon.png);}\n"
"")
        self.SysGain_Cal.setObjectName("SysGain_Cal")
        self.gridLayout_13.addWidget(self.SysGain_Cal, 4, 0, 1, 2)
        self.gridLayout_9.addWidget(self.System_Gain_AT_DCT_Config_Group, 0, 0, 2, 1)
        self.System_Gain_AT_DCT_Figs_Group = QtWidgets.QGroupBox(self.System_Gain_AT_DCT_tab)
        self.System_Gain_AT_DCT_Figs_Group.setObjectName("System_Gain_AT_DCT_Figs_Group")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.System_Gain_AT_DCT_Figs_Group)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.System_Gain_AT_DCT_Figs_scrollArea = QtWidgets.QScrollArea(self.System_Gain_AT_DCT_Figs_Group)
        self.System_Gain_AT_DCT_Figs_scrollArea.setWidgetResizable(True)
        self.System_Gain_AT_DCT_Figs_scrollArea.setObjectName("System_Gain_AT_DCT_Figs_scrollArea")
        self.System_Gain_AT_DCT_Figs_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.System_Gain_AT_DCT_Figs_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 626, 673))
        self.System_Gain_AT_DCT_Figs_scrollAreaWidgetContents.setObjectName("System_Gain_AT_DCT_Figs_scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.System_Gain_AT_DCT_Figs_scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.System_Gain_AT_DCT_Figs_scrollArea.setWidget(self.System_Gain_AT_DCT_Figs_scrollAreaWidgetContents)
        self.gridLayout_8.addWidget(self.System_Gain_AT_DCT_Figs_scrollArea, 1, 0, 1, 3)
        self.gridLayout_9.addWidget(self.System_Gain_AT_DCT_Figs_Group, 0, 1, 1, 4)
        self.System_Gain_PT_Choose.addTab(self.System_Gain_AT_DCT_tab, "")
        self.System_Gain_CVT_tab = QtWidgets.QWidget()
        self.System_Gain_CVT_tab.setObjectName("System_Gain_CVT_tab")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.System_Gain_CVT_tab)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.System_Gain_PT_Choose.addTab(self.System_Gain_CVT_tab, "")
        self.System_Gain_MT_tab = QtWidgets.QWidget()
        self.System_Gain_MT_tab.setObjectName("System_Gain_MT_tab")
        self.System_Gain_PT_Choose.addTab(self.System_Gain_MT_tab, "")
        self.gridLayout_16.addWidget(self.System_Gain_PT_Choose, 0, 0, 1, 1)
        self.MainStackedWidget.addWidget(self.System_Gain_page)
        self.Compare_Result_page = QtWidgets.QWidget()
        self.Compare_Result_page.setObjectName("Compare_Result_page")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.Compare_Result_page)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.History_Data_Choose = QtWidgets.QGroupBox(self.Compare_Result_page)
        self.History_Data_Choose.setMaximumSize(QtCore.QSize(16777215, 60))
        self.History_Data_Choose.setObjectName("History_Data_Choose")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.History_Data_Choose)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.History_Data_Choose_LayH = QtWidgets.QHBoxLayout()
        self.History_Data_Choose_LayH.setSpacing(3)
        self.History_Data_Choose_LayH.setObjectName("History_Data_Choose_LayH")
        self.History_Data_Choose_lab = QtWidgets.QLabel(self.History_Data_Choose)
        self.History_Data_Choose_lab.setMinimumSize(QtCore.QSize(130, 20))
        self.History_Data_Choose_lab.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.History_Data_Choose_lab.setFont(font)
        self.History_Data_Choose_lab.setObjectName("History_Data_Choose_lab")
        self.History_Data_Choose_LayH.addWidget(self.History_Data_Choose_lab)
        self.History_Data_Choose_PlainTextEdit = QtWidgets.QPlainTextEdit(self.History_Data_Choose)
        self.History_Data_Choose_PlainTextEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.History_Data_Choose_PlainTextEdit.setMaximumSize(QtCore.QSize(16777215, 60))
        self.History_Data_Choose_PlainTextEdit.setObjectName("History_Data_Choose_PlainTextEdit")
        self.History_Data_Choose_LayH.addWidget(self.History_Data_Choose_PlainTextEdit)
        self.History_Data_Choose_PushButton = QtWidgets.QPushButton(self.History_Data_Choose)
        self.History_Data_Choose_PushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.History_Data_Choose_PushButton.setObjectName("History_Data_Choose_PushButton")
        self.History_Data_Choose_LayH.addWidget(self.History_Data_Choose_PushButton)
        self.gridLayout_10.addLayout(self.History_Data_Choose_LayH, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.History_Data_Choose, 0, 0, 1, 1)
        self.History_Data_Comp = QtWidgets.QGroupBox(self.Compare_Result_page)
        self.History_Data_Comp.setObjectName("History_Data_Comp")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.History_Data_Comp)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.History_Data_Comp_LayG = QtWidgets.QGridLayout()
        self.History_Data_Comp_LayG.setObjectName("History_Data_Comp_LayG")
        self.History_Data_Comp_scrollArea = QtWidgets.QScrollArea(self.History_Data_Comp)
        self.History_Data_Comp_scrollArea.setWidgetResizable(True)
        self.History_Data_Comp_scrollArea.setObjectName("History_Data_Comp_scrollArea")
        self.History_Data_Comp_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.History_Data_Comp_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 952, 2510))
        self.History_Data_Comp_scrollAreaWidgetContents.setObjectName("History_Data_Comp_scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.History_Data_Comp_scrollAreaWidgetContents)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.History_Data_Comp_graphicsView_5 = QtWidgets.QGraphicsView(self.History_Data_Comp_scrollAreaWidgetContents)
        self.History_Data_Comp_graphicsView_5.setMinimumSize(QtCore.QSize(0, 500))
        self.History_Data_Comp_graphicsView_5.setObjectName("History_Data_Comp_graphicsView_5")
        self.gridLayout_4.addWidget(self.History_Data_Comp_graphicsView_5, 7, 0, 1, 4)
        self.History_Data_Comp_graphicsView_LayG1 = QtWidgets.QGridLayout()
        self.History_Data_Comp_graphicsView_LayG1.setObjectName("History_Data_Comp_graphicsView_LayG1")
        self.gridLayout_4.addLayout(self.History_Data_Comp_graphicsView_LayG1, 0, 0, 1, 1)
        self.History_Data_Comp_graphicsView_1 = QtWidgets.QGraphicsView(self.History_Data_Comp_scrollAreaWidgetContents)
        self.History_Data_Comp_graphicsView_1.setMinimumSize(QtCore.QSize(0, 500))
        self.History_Data_Comp_graphicsView_1.setObjectName("History_Data_Comp_graphicsView_1")
        self.gridLayout_4.addWidget(self.History_Data_Comp_graphicsView_1, 1, 0, 1, 1)
        self.History_Data_Comp_graphicsView_LayG2 = QtWidgets.QGridLayout()
        self.History_Data_Comp_graphicsView_LayG2.setObjectName("History_Data_Comp_graphicsView_LayG2")
        self.gridLayout_4.addLayout(self.History_Data_Comp_graphicsView_LayG2, 0, 1, 1, 1)
        self.History_Data_Comp_graphicsView_LayG5 = QtWidgets.QGridLayout()
        self.History_Data_Comp_graphicsView_LayG5.setObjectName("History_Data_Comp_graphicsView_LayG5")
        self.gridLayout_4.addLayout(self.History_Data_Comp_graphicsView_LayG5, 6, 0, 1, 4)
        self.History_Data_Comp_graphicsView_LayG4 = QtWidgets.QGridLayout()
        self.History_Data_Comp_graphicsView_LayG4.setObjectName("History_Data_Comp_graphicsView_LayG4")
        self.gridLayout_4.addLayout(self.History_Data_Comp_graphicsView_LayG4, 4, 0, 1, 4)
        self.History_Data_Comp_graphicsView_6 = QtWidgets.QGraphicsView(self.History_Data_Comp_scrollAreaWidgetContents)
        self.History_Data_Comp_graphicsView_6.setMinimumSize(QtCore.QSize(0, 500))
        self.History_Data_Comp_graphicsView_6.setObjectName("History_Data_Comp_graphicsView_6")
        self.gridLayout_4.addWidget(self.History_Data_Comp_graphicsView_6, 9, 0, 1, 4)
        self.History_Data_Comp_graphicsView_4 = QtWidgets.QGraphicsView(self.History_Data_Comp_scrollAreaWidgetContents)
        self.History_Data_Comp_graphicsView_4.setMinimumSize(QtCore.QSize(0, 500))
        self.History_Data_Comp_graphicsView_4.setObjectName("History_Data_Comp_graphicsView_4")
        self.gridLayout_4.addWidget(self.History_Data_Comp_graphicsView_4, 5, 0, 1, 4)
        self.History_Data_Comp_graphicsView_LayG3 = QtWidgets.QGridLayout()
        self.History_Data_Comp_graphicsView_LayG3.setObjectName("History_Data_Comp_graphicsView_LayG3")
        self.gridLayout_4.addLayout(self.History_Data_Comp_graphicsView_LayG3, 0, 3, 1, 1)
        self.History_Data_Comp_graphicsView_LayG7 = QtWidgets.QGridLayout()
        self.History_Data_Comp_graphicsView_LayG7.setObjectName("History_Data_Comp_graphicsView_LayG7")
        self.gridLayout_4.addLayout(self.History_Data_Comp_graphicsView_LayG7, 10, 0, 1, 4)
        self.History_Data_Comp_graphicsView_LayG6 = QtWidgets.QGridLayout()
        self.History_Data_Comp_graphicsView_LayG6.setObjectName("History_Data_Comp_graphicsView_LayG6")
        self.gridLayout_4.addLayout(self.History_Data_Comp_graphicsView_LayG6, 8, 0, 1, 4)
        self.History_Data_Comp_graphicsView_7 = QtWidgets.QGraphicsView(self.History_Data_Comp_scrollAreaWidgetContents)
        self.History_Data_Comp_graphicsView_7.setMinimumSize(QtCore.QSize(0, 500))
        self.History_Data_Comp_graphicsView_7.setObjectName("History_Data_Comp_graphicsView_7")
        self.gridLayout_4.addWidget(self.History_Data_Comp_graphicsView_7, 11, 0, 1, 4)
        self.History_Data_Comp_graphicsView_2 = QtWidgets.QGraphicsView(self.History_Data_Comp_scrollAreaWidgetContents)
        self.History_Data_Comp_graphicsView_2.setMinimumSize(QtCore.QSize(0, 500))
        self.History_Data_Comp_graphicsView_2.setObjectName("History_Data_Comp_graphicsView_2")
        self.gridLayout_4.addWidget(self.History_Data_Comp_graphicsView_2, 1, 1, 1, 1)
        self.History_Data_Comp_graphicsView_3 = QtWidgets.QGraphicsView(self.History_Data_Comp_scrollAreaWidgetContents)
        self.History_Data_Comp_graphicsView_3.setMinimumSize(QtCore.QSize(0, 500))
        self.History_Data_Comp_graphicsView_3.setObjectName("History_Data_Comp_graphicsView_3")
        self.gridLayout_4.addWidget(self.History_Data_Comp_graphicsView_3, 1, 3, 1, 1)
        self.History_Data_Comp_scrollArea.setWidget(self.History_Data_Comp_scrollAreaWidgetContents)
        self.History_Data_Comp_LayG.addWidget(self.History_Data_Comp_scrollArea, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.History_Data_Comp_LayG, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.History_Data_Comp, 1, 0, 1, 1)
        self.MainStackedWidget.addWidget(self.Compare_Result_page)
        self.InfoWidget = QtWidgets.QListWidget(self.splitter_centralwidget)
        self.InfoWidget.setObjectName("InfoWidget")
        self.gridLayout_3.addWidget(self.splitter_centralwidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1011, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(30, 24))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actiontest = QtWidgets.QAction(MainWindow)
        self.actiontest.setObjectName("actiontest")
        self.actiontest2 = QtWidgets.QAction(MainWindow)
        self.actiontest2.setObjectName("actiontest2")
        self.menu_Engine_Working_Dist = QtWidgets.QAction(MainWindow)
        self.menu_Engine_Working_Dist.setObjectName("menu_Engine_Working_Dist")
        self.menu_InputData = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.menu_InputData.setFont(font)
        self.menu_InputData.setObjectName("menu_InputData")
        self.menu_CalData = QtWidgets.QAction(MainWindow)
        self.menu_CalData.setObjectName("menu_CalData")
        self.menu_Exit = QtWidgets.QAction(MainWindow)
        self.menu_Exit.setObjectName("menu_Exit")
        self.menu_Guildlines = QtWidgets.QAction(MainWindow)
        self.menu_Guildlines.setObjectName("menu_Guildlines")
        self.menu_ContactUs = QtWidgets.QAction(MainWindow)
        self.menu_ContactUs.setObjectName("menu_ContactUs")
        self.menu_Shifting_Strategy = QtWidgets.QAction(MainWindow)
        self.menu_Shifting_Strategy.setObjectName("menu_Shifting_Strategy")
        self.menu_Speed_Dist = QtWidgets.QAction(MainWindow)
        self.menu_Speed_Dist.setObjectName("menu_Speed_Dist")
        self.action_Data_Viewer = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Image/Icon/find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Data_Viewer.setIcon(icon)
        self.action_Data_Viewer.setObjectName("action_Data_Viewer")
        self.action_System_Gain = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Image/Icon/wave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_System_Gain.setIcon(icon1)
        self.action_System_Gain.setObjectName("action_System_Gain")
        self.action_Compare_Result = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Image/Icon/compare01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Compare_Result.setIcon(icon2)
        self.action_Compare_Result.setObjectName("action_Compare_Result")
        self.menu_Save = QtWidgets.QAction(MainWindow)
        self.menu_Save.setObjectName("menu_Save")
        self.menu_Output_Report = QtWidgets.QAction(MainWindow)
        self.menu_Output_Report.setObjectName("menu_Output_Report")
        self.menu.addAction(self.menu_InputData)
        self.menu.addAction(self.menu_Save)
        self.menu.addAction(self.menu_Output_Report)
        self.menu.addSeparator()
        self.menu.addAction(self.menu_Exit)
        self.menu_3.addAction(self.menu_Engine_Working_Dist)
        self.menu_3.addAction(self.menu_Shifting_Strategy)
        self.menu_3.addAction(self.menu_Speed_Dist)
        self.menu_2.addAction(self.menu_CalData)
        self.menu_4.addAction(self.menu_Guildlines)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.menu_ContactUs)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.toolBar.addAction(self.action_Data_Viewer)
        self.toolBar.addAction(self.action_System_Gain)
        self.toolBar.addAction(self.action_Compare_Result)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.MainStackedWidget.setCurrentIndex(1)
        self.System_Gain_PT_Choose.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.System_Gain_AT_DCT_Vspd, self.System_Gain_AT_DCT_Ped)
        MainWindow.setTabOrder(self.System_Gain_AT_DCT_Ped, self.System_Gain_AT_DCT_Acc)
        MainWindow.setTabOrder(self.System_Gain_AT_DCT_Acc, self.System_Gain_AT_DCT_Gear)
        MainWindow.setTabOrder(self.System_Gain_AT_DCT_Gear, self.System_Gain_AT_DCT_Toq)
        MainWindow.setTabOrder(self.System_Gain_AT_DCT_Toq, self.System_Gain_AT_DCT_Fuel)
        MainWindow.setTabOrder(self.System_Gain_AT_DCT_Fuel, self.System_Gain_AT_DCT_EnSpd)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Data_Viewer_CheckBox_groupBox.setTitle(_translate("MainWindow", "信号选取"))
        self.Infolabel.setText(_translate("MainWindow", "请先选取数据"))
        self.System_Gain_AT_DCT_Config_Group.setTitle(_translate("MainWindow", "配置"))
        self.System_Gain_AT_DCT_Features_lab.setText(_translate("MainWindow", "字段选择："))
        self.System_Gain_AT_DCT_Time_lab.setText(_translate("MainWindow", "时间(s)"))
        self.System_Gain_AT_DCT_Vspd_lab.setText(_translate("MainWindow", "车速(km/h)"))
        self.System_Gain_AT_DCT_Ped_lab.setText(_translate("MainWindow", "油门(-)"))
        self.System_Gain_AT_DCT_Acc_lab.setText(_translate("MainWindow", "加速度(g)"))
        self.System_Gain_AT_DCT_Gear_lab.setText(_translate("MainWindow", "档位(-)"))
        self.System_Gain_AT_DCT_Toq_lab.setText(_translate("MainWindow", "扭矩(N.m)"))
        self.System_Gain_AT_DCT_Fuel_lab.setText(_translate("MainWindow", "喷油量(ul/s)"))
        self.System_Gain_AT_DCT_EnSpd_lab.setText(_translate("MainWindow", "发动机转速(rpm)"))
        self.System_Gain_AT_DCT_TbSpd_lab.setText(_translate("MainWindow", "涡轮转速(rpm)"))
        self.System_Gain_AT_DCT_AddInput.setText(_translate("MainWindow", "附加输入："))
        self.System_Gain_AT_DCT_StableVspd_lab.setText(_translate("MainWindow", "稳态车速："))
        self.System_Gain_AT_DCT_StableVspd_TextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">输入稳态车速，以空格为间隔</p></body></html>"))
        self.System_Gain_AT_DCT_StablePed_lab.setText(_translate("MainWindow", "踏板信号："))
        self.System_Gain_AT_DCT_StablePed_TextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">输入踏板信号，以空格为间隔</p></body></html>"))
        self.SysGain_Cal.setText(_translate("MainWindow", "计  算"))
        self.System_Gain_AT_DCT_Figs_Group.setTitle(_translate("MainWindow", "输出图片"))
        self.System_Gain_PT_Choose.setTabText(self.System_Gain_PT_Choose.indexOf(self.System_Gain_AT_DCT_tab), _translate("MainWindow", "AT/DCT"))
        self.System_Gain_PT_Choose.setTabText(self.System_Gain_PT_Choose.indexOf(self.System_Gain_CVT_tab), _translate("MainWindow", "CVT"))
        self.System_Gain_PT_Choose.setTabText(self.System_Gain_PT_Choose.indexOf(self.System_Gain_MT_tab), _translate("MainWindow", "MT"))
        self.History_Data_Choose.setTitle(_translate("MainWindow", "计算结果导入"))
        self.History_Data_Choose_lab.setText(_translate("MainWindow", "历史测试数据导入："))
        self.History_Data_Choose_PushButton.setText(_translate("MainWindow", "对比"))
        self.History_Data_Comp.setTitle(_translate("MainWindow", "对比图"))
        self.menu.setTitle(_translate("MainWindow", "文件 (File)"))
        self.menu_3.setTitle(_translate("MainWindow", "绘图 (Ploting)"))
        self.menu_2.setTitle(_translate("MainWindow", "计算 (Calculation)"))
        self.menu_4.setTitle(_translate("MainWindow", "帮助 (Help)"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actiontest.setText(_translate("MainWindow", "test"))
        self.actiontest2.setText(_translate("MainWindow", "test2"))
        self.menu_Engine_Working_Dist.setText(_translate("MainWindow", "发动机工况点分布 Engine Work Point Dist."))
        self.menu_InputData.setText(_translate("MainWindow", "导入测试数据 Input Test Data"))
        self.menu_CalData.setText(_translate("MainWindow", "求解 Solution"))
        self.menu_Exit.setText(_translate("MainWindow", "退出 Exit"))
        self.menu_Guildlines.setText(_translate("MainWindow", "操作指南 Guildlines"))
        self.menu_ContactUs.setText(_translate("MainWindow", "联系作者 Contact Us!"))
        self.menu_Shifting_Strategy.setText(_translate("MainWindow", "换挡策略分布 Shifting Strategy Dist."))
        self.menu_Speed_Dist.setText(_translate("MainWindow", "速度分布 Speed Dist."))
        self.action_Data_Viewer.setText(_translate("MainWindow", "Data Viewer"))
        self.action_Data_Viewer.setToolTip(_translate("MainWindow", "Data_Viewer"))
        self.action_Data_Viewer.setShortcut(_translate("MainWindow", "F1"))
        self.action_System_Gain.setText(_translate("MainWindow", "System Gain"))
        self.action_System_Gain.setToolTip(_translate("MainWindow", "System_Gain"))
        self.action_System_Gain.setShortcut(_translate("MainWindow", "F2"))
        self.action_Compare_Result.setText(_translate("MainWindow", "Compare Result"))
        self.action_Compare_Result.setToolTip(_translate("MainWindow", "Compare_Result"))
        self.action_Compare_Result.setShortcut(_translate("MainWindow", "F3"))
        self.menu_Save.setText(_translate("MainWindow", "保存计算结果 Save Data"))
        self.menu_Output_Report.setText(_translate("MainWindow", "导出计算报告 Output Report"))


